### ISSUE TITLE
did you check the output hash of twin-bcrypt conforms to bcrypt?

### ISSUE THREAD

**Issue by nelsonic** [timkuijsten/node-bcrypt-speed#1]
Hi @timkuijsten 
did you do a comparison of **twin-bcrypt** and **bcrypt** to confirm twin conforms to spec?
https://github.com/timkuijsten/node-bcrypt-speed/blob/master/bcrypt-speed.js#L60

I tried:

``` js
var twinbcrypt = require('twin-bcrypt');
var bcrypt       = require('bcrypt');
var assert       = require('assert');

var salt  = twinbcrypt.genSalt(12);
var hash = twinbcrypt.hashSync('hello', salt);

assert.equal(bcrypt.compareSync("hello", hash), true, "twin-bcrypt is compatible with bcrypt");
```

Which sadly fails... :cry: 
Any insight you can provide would be much appreciated!

**Comment by timkuijsten** [comment]
@nelsonic actually I did not. This test of yours surprises me as well. I would contact the authors of twin-bcrypt. I've found them to be very responsive [0].

[0] https://github.com/fpirsch/twin-bcrypt/issues/1

**Comment by timkuijsten** [comment]
aah, i see you already did :)
